---
- name: Copy zabbix repo
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
    dest: /tmp/
    timeout: 30
    validate_certs: false
- name: Install zabbix repo
  ansible.builtin.package:
    name: /tmp/zabbix-release-6.0-4.el8.noarch.rpm
    state: present
    disable_gpg_check: true
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
- name: clean dnf cash
  command: dnf clean all



- name: Get pgdg-redhat-repo-latest.noarch.rpm
  ansible.builtin.get_url:
    url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    dest: /tmp/
    timeout: 30
    validate_certs: false
- name: Install PostgreSQL repository
  ansible.builtin.package:
    name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
- name: disable default postgres
  command: dnf -qy module disable postgresql
- name: clean cashd
  command: dnf clean all
- name: Install postgres client to export initial DB
  ansible.builtin.dnf:
    name: 
      - postgresql15
    state: present


- name: Install Zabbix server
  ansible.builtin.dnf:
    name: 
      - zabbix-server-pgsql 
      - zabbix-sql-scripts 
      - zabbix-selinux-policy
      - policycoreutils-python-utils
    state: present


- name: Export initial Zabbix DB to postgres cluster
  shell: |
    zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | PGPASSWORD=zabbix psql -U zabbix -h {{ lookup('ansible.builtin.env', 'INTERNAL_IP_NLB2')}} -d zabbix
  args: 
    executable: /bin/bash  
  async: 1000 


- name: Adjust selinux
  shell: |
    semanage permissive -a zabbix_t
  args: 
    executable: /bin/bash


- name: Copy Zabbix server conf
  ansible.builtin.template:
    src: templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf


- name: Enable and restart Zabbix server
  ansible.builtin.service:
    name: zabbix-server
    enabled: true
    state: restarted
